algoritmo "Problema Crescente"
// Função :
// Autor :
// Data : 17/06/2022
// Seção de Declarações 
var
numero1,numero2: inteiro
inicio
// Seção de Comandos 
escreva("Digite dois numeros:")
leia(numero1,numero2)

enquanto numero1<>numero2 faca
se numero1>numero2 entao
escreval("DECRESCENTE!")
senao
escreval("CRESCENTE!")
fimse
escreval("Digite outros dois numeros: ")
leia(numero1,numero2)
fimenquanto


fimalgoritmo
